version: '3'

includes:
  home: 
    taskfile: ./home
    internal: true

env: 
  ROOT_DIR: '{{ .TASKFILE_DIR }}'

tasks:
  setup:
    desc: Setup working env for device. 
    dir: '{{ .TASKFILE_DIR }}'
    vars: 
      DISTRO_ID: 
        sh: cat /etc/*-release | grep DISTRIB_ID | sed 's/^DISTRIB_ID=//'
      DEVICE_TYPE: 
        sh: |
          if [[ -n '{{ .DEVICE_TYPE}}' ]]; then 
            echo {{ .DEVICE_TYPE }}
          elif [[ -d /usr/share/xsessions ]] && [[ -n "$(ls -A /usr/share/xsessions/)" ]]; then
            echo PC
          else
            echo SERVER
          fi
      IS_SUDOER:
        sh: |
          if [[ -n '{{ .IS_SUDOER }}' ]]; then 
            echo {{ .IS_SUDOER }}
          elif [[ -n $(groups | grep --only-matching sudo) ]]; then 
            echo TRUE
          else 
            echo FALSE
          fi
    preconditions: 
      # Validate `DEVICE_TYPE`
      - sh: "[[ '{{ .DEVICE_TYPE }}' == 'PC' || '{{ .DEVICE_TYPE }}' == 'SERVER' ]]"
        msg: "'DEVICE_TYPE' must be 'PC' or 'SERVER', not '{{ .DEVICE_TYPE }}'"
      
      # Validate `DISTRO_ID`
      - sh: "[[ '{{ .DISTRO_ID }}' == 'Ubuntu' ]]"
        msg: "Not supported for '{{ .DISTRO_ID }}'"

      # Validate `IS_SUDOER`
      - sh: "[[ '{{ .IS_SUDOER }}' == 'TRUE' || '{{ .IS_SUDOER }}' == 'FALSE' ]]"
        msg: "'IS_SUDOER' must be 'TRUE' or 'FALSE', not '{{ .IS_SUDOER }}'"
    
    env: 
      DEVICE_TYPE: '{{ .DEVICE_TYPE }}'
      DISTRO_ID: '{{ .DISTRO_ID }}'
      IS_SUDOER: '{{ .IS_SUDOER }}'
    cmds: 
      # TODO: PROMPT Confirm
      - echo hihi $DEVICE_TYPE $DISTRO_ID $IS_SUDOER
      - cmd: |
          if [[ '{{ .DEVICE_TYPE }}' == 'PC' ]] && [[ -n '$(ls -A /usr/share/xsessions/)' ]]; then
            ${ROOT_DIR}/gnome/setup.sh
          fi
      - task: home:init
      
      # - task: __home.init__
      # - task: __terminal__
      # - task: __home.setup__
      #   vars:
      #     DEVICE_TYPE:
      #       ref: .DEVICE_TYPE
  # __home.init__:
  #   desc: Init ~ dir
  #   dir: '{{ .TASKFILE_DIR }}'
  #   cmds:
  #     - ${ROOT_DIR}/home/init.sh
  # __terminal__:
  #   desc: Setup terminal
  #   dir: '{{ .TASKFILE_DIR }}'
  #   cmds:
  #     - ${ROOT_DIR}/terminal/setup.sh
  # __home.setup__:
  #   desc: Setup ~ dir
  #   requires:
  #     vars:
  #       - DEVICE_TYPE
  #   cmds:
  #     - ${ROOT_DIR}/home/setup.sh