version: '3'

tasks:
  init: 
    desc: Init ~ dir
    # requires:
    #   vars:
    #     - ROOT_DIR
    cmds: 
      - mkdir -p ~/.local
      - mkdir -p ~/workspace
      - for:
          - .local/envs
          - .fonts
        cmd: |
          echo {{ .ITEM }}
          # if [ -d {{ .ITEM }} ]; then rm -rf {{ .ITEM }}; fi
          # ln -sf ${ .TASKFILE_DIR }/.fonts ~/.fonts
      # - for:
      #     var: BINS
      #   cmd: hu
  init&verify:
    desc: task init and verify
    deps:
      - init
    cmds: 
      - echo DONE!
  setup: 
    desc: Setup ~ dir - bins and configs
    vars:
      BINS: 
        sh: ls -A {{ .TASKFILE_DIR }}/.local/bin/