_ui: &ui
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  reactive: false
  noIcons: false
  defaultsToFullScreen: false

_shellPod: &shellPod
  image: busybox:1.35.0
  namespace: default
  limits:
    cpu: 100m
    memory: 100Mi
  tty: true

_defaultConfigs: &defaultConfigs
  screenDumpDir: ~/.local/state/k9s/screen-dumps
  # Enable periodic refresh of resource browser windows. Default false
  liveViewAutoRefresh: false
  # Represents ui poll intervals. Default 2secs
  refreshRate: 2
  # Number of retries once the connection to the api-server is lost. Default 15.
  maxConnRetry: 5
  # Specifies if modification commands like delete/kill/edit are disabled. Default is false
  readOnly: false
  # Toggles whether k9s should exit when CTRL-C is pressed. When set to true, you will need to exist k9s via the :quit command. Default is false.
  noExitOnCtrlC: false
  # Toggles whether k9s should check for the latest revision from the Github repository releases. Default is false.
  skipLatestRevCheck: false
  # Disable count pods while in node view. Default is false.
  disablePodCounting: false
  # ImageScan config changed from v0.29.0!
  imageScans:
    enable: false
    # Exclusions excludes namespaces or specific workload labels
    exclusions:
      # Exclude the following namespaces for image vulscans!
      namespaces: []
      # Exclude pods with the following labels from image vulscans!
      labels: {}
  # Logs configuration
  logger:
    # Defines the number of lines to return. Default 100
    tail: 100
    # Defines the total number of log lines to allow in the view. Default 1000
    buffer: 5000
    # Represents how far to go back in the log timeline in seconds. Setting to -1 will tail logs. Default is -1.
    sinceSeconds: -1
    # Go full screen while displaying logs. Default false
    fullScreen: false
    # Toggles log line wrap. Default false
    textWrap: false
    # Toggles log line timestamp info. Default false
    showTime: true
  # Global memory/cpu thresholds. When set will alert when thresholds are met.
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70



# MAIN PATH
k9s:
  <<: *defaultConfigs

  liveViewAutoRefresh: true
  
  ui: *ui    
  shellPod: &shellPod

    
  # featureGates: 
  #   nodeShell: true
  

