# working_directory = "$HOME/workspace"
live_config_reload = true

[shell]
program = "/usr/bin/bash"
args = [
    "-ic", 
    "sleep 0.2 && zellij "
]

[env]

[window]
opacity = 0.8
decorations = "None"