name: SERVER-UBUNTU-NON_SUDO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu-2004:
    container: "ubuntu:20.04"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create user nonroot and switch
        run: |
          useradd -md /home/nonroot -s /bin/bash nonroot
          su nonroot
      - name: Run setup
        run: ./setup
  archlinux:
    container: archlinux:base
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Create user nonroot and switch
        run: |
          useradd -md /home/nonroot -s /bin/bash nonroot
          su nonroot
      - name: Run setup
        run: ./setup
