name: SERVER-UBUNTU-SUDO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu-2004:
    container: "ubuntu:20.04"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install sudo
        run: |
          apt-get update
          apt-get install -y sudo
      - name: Create sudoer and switch
        run: |
          useradd -md /home/admin -s /bin/bash admin
          usermod -aG sudo admin
          su admin
      - name: Check id and groups
        run: |
          echo "ID: $(whoami)"
          echo "Groups: $(groups)"
      - name: Run init
        run: ./home/.local/bin/task init
  archlinux:
    container: archlinux:base
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Run init
        run: ./home/.local/bin/task init
