name: SERVER-UBUNTU-SUDO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu-2004:
    container: "ubuntu:20.04"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install sudo
        run: |
          apt-get update
          apt-get install -y sudo
      - name: Add groups
        run: usermod -aG sudo root
      - name: Switch to get groups
        run: sudo su - root
      - name: check groups
        run: groups
      - name: Run init
        run: ./home/.local/bin/task init
  archlinux:
    container: archlinux:base
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Run init
        run: ./home/.local/bin/task init
